Fixed for AAOS Hardware Form factor.
When running ATS bfg performance test, we were seeing following issue
java.lang.RuntimeException: Failed to determine the current device.
MANUFACTURER="Intel" BRAND="intel" MODEL="AOSP at
com.google.android.apps.gsa.testing.ui.support.AndroidPlatform
.getCurrentDevice(AndroidPlatform.java:154)
at com.google.android.apps.gsa.testing.ui.support.AppFlowEventMonitor
.isAutoDevice(AppFlowEventMonitor.java:50)

Above error we were seeing due to missing below property
ro.hardware.type=automotive

Tests:
Run ATS bfg test. Above error should not come.

Tracked-On: OAM-112883
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>