Fixed for crashe during Monkey test run.
Following crash were observed
java.lang.NullPointerException: Attempt to invoke virtual method
'void com.android.systemui.statusbar.phone.NotificationPanelView
Controller.setQsScrimEnabled(boolean)' on a null object reference

Check for null condition, so during monkey test run, if view is
destroyed (which is very rare in manual test), then it can safely
handle.

Tests:
Run monkey test and observe, test is pass.

Tracked-On: OAM-114271
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>