Fixed for crash in Contacts app during Monkey test run.
Observed below crash-
java.lang.RuntimeException: android.os.DeadObjectException: Transaction
failed on small parcel; remote process probably died, but this could
also be caused by running out of binder buffer space
    at android.provider.ContactsContract.nullSafeCall
(ContactsContract.java:10310)
    at android.provider.ContactsContract.-$$Nest$smnullSafeCall
(Unknown Source:0)
    at android.provider.ContactsContract$SimContacts.getSimAccounts
(ContactsContract.java:8472)
    at com.android.contacts.util.DeviceLocalAccountTypeFactory$Default
.classifyAccount(DeviceLocalAccountTypeFactory.java:74)
    at com.android.contacts.util.DeviceLocalAccountTypeFactory$Default
.getAccountType(DeviceLocalAccountTypeFactory.java:88)

Release the provider if there is no other reason for keeping it active.

Tests: Run monkey test. There no crash has observed.

Tracked-On: OAM-122770
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>