Fix error for unused private field
Moving unused private field to public
error: private field 'tcc_offset_checked' is not used [-Werror,-Wunused-private-field]
error: private field 'tcc_offset_low' is not used [-Werror,-Wunused-private-field]

Tracked-On:
Signed-off-by: rugnathr <rugnath.ram@intel.com>