Fixed for crash in Gallery during monkey test.
Fragment Activity does not support action bar by default. Adding
toolbar in layout to create custom action bar.

Crash log snippet looks like below:
java.lang.NullPointerException: Attempt to invoke virtual method
'void android.app.ActionBar.setDisplayOptions(int)' on a null object reference
at com.android.gallery3d.filtershow.FilterShowActivity.loadXML(FilterShowActivity.java:352)

Test: run monkey test, no crash happen.

Tracked-On: OAM-122773
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>
Signed-off-by: Xu Bing <bing.xu@intel.com>