Fix crash in Webview Browser during MonkeyTest
Getting below crash when running monkey test:
 java.lang.RuntimeException: StrictMode ThreadPolicy violation
 Caused by: android.os.strictmode.UnbufferedIoViolation

Allow UnbufferedIo in StrictMode builder.

Test Done: Boot check, webview is working
Tracked-On: OAM-118786
Signed-off-by: Salini Venate <salini.venate@intel.com>