WA: Fix Monkey Test Failure in Gallery App
Monkey Test reported below error:
java.lang.IllegalStateException: Can not perform this
action after onSaveInstanceState
at com.android.gallery3d.filtershow.editors
      .EditorPanel.showImageStatePanel

Use commitAllowingStateLoss() instead of commit() so
that it will not throw an exception if state loss occurs.

Tracked-On: OAM-115689
Signed-off-by: Salini Venate <salini.venate@intel.com>