[PATCH] Fixed crash in DeskClock during monkey test.
Getting below crash when running monkey test-:
java.lang.NullPointerException: Parameter specified as non-null is null:
method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter event
at com.android.deskclock.LabelDialogFragment$ImeDoneListener.onEditorAction(Unknown Source:7)

event parameter is currently declared as non null. it can be null also,
So declaring it as null parameter.

Tracked-On: OAM-129799
Signed-off-by: rnaidu <ramya.v.naidu@intel.com>