Fixed for crash in Usb Handler during monkey test.
Using locked mechanism in code block instead of syncronized method.

Crash log snippet looks like below:
Getting below crash when running monkey test-:
java.lang.RuntimeException: Unable to resume activity
{android.car.usb.handler/android.car.usb.handler.UsbHostManagementActivity}
: java.lang.IllegalStateException: Cannot perform this operation
because the connection pool has been closed.

Tracked-On: OAM-111150
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>