WA - Fix Monkey Test crash in DeskClock
Below crash was seen during MonkeyTest:
java.lang.IllegalStateException: FragmentManager
is already executing transactions.

Use commitNowAllowingStateLoss instead of commitAllowingStateLoss.
commitNowAllowingStateLoss executes the transaction immediately
on the calling thread unlike commitAllowingStateLoss which schedules
the transaction to be executed asynchronously on the main thread.

NOTE: commitNowAllowingStateLoss may potentially lead to ANR if
the transaction takes a long time to execute. If any ANR is seen
in future tests this patch needs to be revisited.

Tests Done: No crash observed in 2 hr monkey test run
            for com.android.deskclock.

Tracked-On: OAM-116600
Signed-off-by: Salini Venate <salini.venate@intel.com>