Fixed for crash in webview_shell during monkey test.
Getting below crash when running monkey test-:
FATAL EXCEPTION: main
Process: org.chromium.webview_shell, PID: 22973
java.lang.RuntimeException: StrictMode ThreadPolicy violation
Caused by: android.os.strictmode.DiskWriteViolation

Added StrictMode ThreadPolicy for disk write.

Tracked-On: OAM-110732
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>