Using gcc/bin fron Android-12
Use for Clang-14 for building kernelflinger was giving
below error:
error: invalid output format: 'efi-app-x86_64'

LLVM Open bug: https://github.com/llvm/llvm-project/issues/39964

So we are using gcc/bin from Android-12 as a WA.

Change-Id: I59a22bc957015d35f8d11396fc339a74494cd0bb
Signed-off-by: svenate <salini.venate@intel.com>