Fixed crash in Gallery during monkey test run.
Observed following crash during monkey test run
android.os.FileUriExposedException: file:///storage/emulated/14/Movies
/MUTE_20240606_225943.mp4 exposed beyond app through Intent.getData()

Porting fix from open source-
fix b/218791647 [AOSP] Gallery app crash when press on Mute button and
saving trimmed video reason for crash was an api change in sdk 24
https://developer.android.com/google/play/requirements/target-sdk
fixed thi issue following https://developer.android.com/training/secure
-file-sharing/setup-sharing
    + Specify file provider in manifest
    + Specify shareable directories
    + Generate uri with FileProvider

ChangeId- I34190720790e0b69d6695474461e461b9c6f61e5

Tests: Compiled and launched Gallery app successfully.

Tracked-On: OAM-120512
Signed-off-by: Ankit Agarwal <ankit.agarwal@intel.com>